name: Test and Deploy Hexo

on:
  permissions:
    contents: write
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Hexo repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Hexo dependencies
        run: |
          cd blog
          npm ci

      - name: Generate Hexo site
        run: |
          cd blog
          npx hexo generate

      - name: Checkout Playwright test repository
        uses: actions/checkout@v3
        with:
          repository: ChrisAbdo/IS373-PW
          path: IS373-PW

      - name: Install Playwright dependencies
        working-directory: IS373-PW
        run: npm ci

      - name: Install Playwright browsers
        working-directory: IS373-PW
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: IS373-PW
        run: npx playwright test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'

    steps:
      - name: Checkout Hexo repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: |
          cd blog
          npm ci

      - name: Generate Hexo site
        run: |
          cd blog
          npx hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog/public
          publish_branch: gh-pages
