name: Test and Deploy Hexo Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Hexo repository again (to prevent loss of state)
      - name: Checkout Hexo repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Make sure it matches your environment

      # Install Hexo and dependencies
      - name: Install Hexo and dependencies
        run: |
          cd blog
          npm install hexo-cli -g
          npm install

      # Generate the static website
      - name: Generate Hexo site
        run: |
          cd blog
          hexo generate

      # Deploy to GitHub Pages
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.ACTIONS_SECRET }}
      #     publish_dir: ./blog/public # Hexo outputs the generated files to the 'public' directory inside 'blog'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
